version: '3.7'
services: 
    online-store: 
        container_name: online-store
        build: .    
        ports:
            - 9001:9001
        env_file:
            - .env
        restart: always
